# Generated by Django 5.0.1 on 2025-11-05 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddField(
            model_name='userfavoritestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='products.store'),
        ),
        migrations.AddField(
            model_name='userfavoritestore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_key_291dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritestore',
            unique_together={('user', 'store')},
        ),
    ]
