# Generated by Django 5.0.1 on 2025-11-07 09:41

import analytics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.CharField(default=analytics.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('total_scans', models.IntegerField(default=0, help_text='Total times this product was scanned')),
                ('total_quantity', models.IntegerField(default=0, help_text='Total quantity purchased')),
                ('total_revenue', models.FloatField(default=0.0, help_text='Total revenue generated in RSD')),
                ('unique_users', models.IntegerField(default=0, help_text='Unique users who purchased')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Analytics',
                'verbose_name_plural': 'Product Analytics',
                'db_table': 'product_analytics',
                'ordering': ['-total_scans'],
            },
        ),
        migrations.CreateModel(
            name='StoreAnalytics',
            fields=[
                ('id', models.CharField(default=analytics.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('total_scans', models.IntegerField(default=0, help_text='Total number of receipt scans')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Total points earned by all users')),
                ('total_points_redeemed', models.IntegerField(default=0, help_text='Total points redeemed/used')),
                ('unique_users', models.IntegerField(default=0, help_text='Unique users who scanned receipts')),
                ('total_revenue', models.FloatField(default=0.0, help_text='Total revenue in RSD')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.store')),
            ],
            options={
                'verbose_name': 'Store Analytics',
                'verbose_name_plural': 'Store Analytics',
                'db_table': 'store_analytics',
                'ordering': ['-total_scans'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.CharField(default=analytics.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of activity')),
                ('total_scans', models.IntegerField(default=0, help_text='Total scans on this date')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Total points earned')),
                ('total_points_redeemed', models.IntegerField(default=0, help_text='Total points redeemed')),
                ('active_users', models.IntegerField(default=0, help_text='Number of active users')),
                ('new_users', models.IntegerField(default=0, help_text='Number of new registrations')),
                ('new_products_scanned', models.IntegerField(default=0, help_text='New unique products scanned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='user_activi_date_fa7ef4_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='StoreProductRanking',
            fields=[
                ('id', models.CharField(default=analytics.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Product name for unmatched items', max_length=255)),
                ('scan_count', models.IntegerField(default=0, help_text='Number of times scanned')),
                ('total_quantity', models.IntegerField(default=0, help_text='Total quantity purchased')),
                ('total_revenue', models.FloatField(default=0.0, help_text='Total revenue in RSD')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_rankings', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rankings', to='products.store')),
            ],
            options={
                'verbose_name': 'Store Product Ranking',
                'verbose_name_plural': 'Store Product Rankings',
                'db_table': 'store_product_rankings',
                'ordering': ['store', '-scan_count'],
                'indexes': [models.Index(fields=['store', '-scan_count'], name='store_produ_store_i_27bd7b_idx')],
                'unique_together': {('store', 'product_name')},
            },
        ),
        migrations.CreateModel(
            name='UserStoreActivity',
            fields=[
                ('id', models.CharField(default=analytics.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('scan_count', models.IntegerField(default=0, help_text='Number of scans by this user')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Total points earned')),
                ('total_spent', models.FloatField(default=0.0, help_text='Total amount spent in RSD')),
                ('first_scan', models.DateTimeField(blank=True, null=True)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='products.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Store Activity',
                'verbose_name_plural': 'User Store Activities',
                'db_table': 'user_store_activities',
                'ordering': ['store', '-scan_count'],
                'indexes': [models.Index(fields=['store', '-scan_count'], name='user_store__store_i_b044e2_idx'), models.Index(fields=['user'], name='user_store__user_id_80060d_idx')],
                'unique_together': {('user', 'store')},
            },
        ),
    ]
