# Generated by Django 5.0.1 on 2025-11-05 19:36

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.CharField(default=reviews.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('receipt_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
