# Generated by Django 5.0.1 on 2025-11-05 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['user'], name='review_requ_user_id_33b085_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['status'], name='review_requ_status_b09874_idx'),
        ),
    ]
