from django.contrib import admin
from .models import Product, Store, UserFavoriteStore, ApiKey


@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    """Admin interface for Product model."""

    list_display = ['name', 'points', 'status', 'created_at']
    list_filter = ['status', 'created_at']
    search_fields = ['name', 'id']
    ordering = ['name']
    readonly_fields = ['id', 'created_at', 'updated_at']

    fieldsets = (
        (None, {'fields': ('id', 'name', 'points', 'status')}),
        ('Timestamps', {'fields': ('created_at', 'updated_at')}),
    )


@admin.register(Store)
class StoreAdmin(admin.ModelAdmin):
    """Admin interface for Store model."""

    list_display = ['name', 'location', 'created_at']
    search_fields = ['name', 'location', 'id']
    ordering = ['name']
    readonly_fields = ['id', 'created_at', 'updated_at']

    fieldsets = (
        (None, {'fields': ('id', 'name', 'location')}),
        ('Timestamps', {'fields': ('created_at', 'updated_at')}),
    )


@admin.register(UserFavoriteStore)
class UserFavoriteStoreAdmin(admin.ModelAdmin):
    """Admin interface for UserFavoriteStore model."""

    list_display = ['user', 'store', 'created_at']
    list_filter = ['created_at']
    search_fields = ['user__email', 'store__name']
    ordering = ['-created_at']
    readonly_fields = ['id', 'created_at']

    fieldsets = (
        (None, {'fields': ('id', 'user', 'store')}),
        ('Timestamps', {'fields': ('created_at',)}),
    )


@admin.register(ApiKey)
class ApiKeyAdmin(admin.ModelAdmin):
    """Admin interface for ApiKey model."""

    list_display = ['name', 'user', 'active', 'created_at', 'last_used']
    list_filter = ['active', 'created_at', 'last_used']
    search_fields = ['name', 'user__email', 'key']
    ordering = ['-created_at']
    readonly_fields = ['id', 'key', 'created_at', 'last_used']

    fieldsets = (
        (None, {'fields': ('id', 'user', 'name', 'key', 'active')}),
        ('Timestamps', {'fields': ('created_at', 'last_used')}),
    )

    def save_model(self, request, obj, form, change):
        """Auto-generate API key on creation."""
        if not change:  # Only on creation
            # Key will be auto-generated by model's save method
            pass
        super().save_model(request, obj, form, change)
