# Generated by Django 5.0.1 on 2025-11-05 19:36

import django.db.models.deletion
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.CharField(default=transactions.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('matched', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transaction_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=transactions.models.generate_cuid, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('total_points', models.IntegerField()),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('receipt_data', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.store')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
