# Generated by Django 5.0.1 on 2025-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
