# Generated by Django 5.0.1 on 2025-11-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
