# Generated by Django 5.0.1 on 2025-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_total_amount_transactionitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='review_status',
            field=models.CharField(choices=[('none', 'No Review'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='none', max_length=20),
        ),
    ]
